### PR TITLE
Fix IllegalArg exception when getting random phrase

### LINKED ISSUE #15: Rebirth of the Night Array Index error.
Rebirth of the Night modpack version: Rebirth of the Night-2.76.2
Forge: 14.23.5.2847
[crash-2020-03-30_20.47.37-server.txt](https://github.com/Clownvin/Living-Enchantment/files/4402705/crash-2020-03-30_20.47.37-server.txt)

### PR DESCRIPTION
**Pull request by democat3457**
This should also probably be fixed on 1.13 and 1.14.
Should fix #15

### CODE REVIEW

**Comment by Clownvin** [comment]
I'm pretty positive that this would only introduce another bug. If you look at the documentation for Math.random(), https://docs.oracle.com/javase/7/docs/api/java/lang/Math.html#random(), you can see that it returns 0.0 inclusive to 1.0 exclusive. So it will never equal 1.0, just very close to it. When you cast to integer after applying Math.random, it's basically the same as applying Math.floor, which will round down to the nearest integer. Due to this, the original code can only produce a value between 0 and length - 1. Subtracting one before multiplication by Math.random() could potentially lead to negative numbers, if the length was 0. 

I took a glance at #15, and it appears to happen on "index 0", which suggests that the array is empty, which is definitely very interesting.

**Comment by democat3457** [comment]
Ah I see.

**Comment by democat3457** [comment]
I suppose you could have a check for whether the phrase list is empty and return a default string? That's probably a last resort though.

**Comment by Clownvin** [comment]
That would work, but it wouldn't solve the real issue of the empty array. My guess is that it's probably a custom personality? And maybe they just didn't add that section properly. Checking for length and returning a default string, maybe "herobrine says hi", or something herobrine related, could be a good bandaid.

**Comment by democat3457** [comment]
Turns out the issue was indeed caused by an incomplete personality config. I've added a default in the latest commit and removed the `- 1`

**Comment by democat3457** [comment]
bump

**Comment by Clownvin** [comment]
I'm really busy with work right now. I'll see if I can get to this later this weekend.

**Comment by democat3457** [comment]
Aight

**Comment by SandwichHorror** [comment]
Whoops. I came to the same conclusion blessed democat came to a whole week ago. #18 is the most concise version of the actual bug, even with a properly configured personality

**Comment by democat3457** [comment]
bump

**Comment by democat3457** [comment]
bump

**Review by Clownvin — CHANGES_REQUESTED** [review]
I know I used ternary operators, and bad code style all over this mod (haha), but I think it's time to start doing it right and make it good code. Lets make the ternary an if. Also, sorry for the delay haha. I got caught up in life and work. I probably won't actively make new content, but I'll fix and approve select PRs I think.

If I get into 1.15, I might make a new version for that too.

**Review by Clownvin — DISMISSED** [review]

**Comment by Clownvin** [comment]
Current changes will crash, but it's arguably better. I'll add something real quick.

**Review by Clownvin — APPROVED** [review]

**Comment by democat3457** [comment]
~~but ternaries are good~~

**Pull request merged**
